export { default as Navbar } from "./navbar";
export { default as Hero } from "./hero";
export { default as Button } from "./button";
export { default as Menu } from "./menu";
export { default as Event } from "./event";
export { default as Eye } from "./eye";
export { default as Slider } from "./slider";
export { default as Sticky } from "./sticky";
export { default as WhoWeAre } from "./who-we-are";